#!/bin/bash

# Hardcoded defaults
#	Immutable
main_directory="~/.playlister/"
config_file="${main_directory}playlister.conf"
config_file_bak="${config_file}.bak"
database="${main_directory}playlister.db"
database_bak="${database}.bak"
helpfile="${main_directory}playlister.help"
#	Mutable
playlist_directory="${main_directory}playlists/"
mp3_directory="/mp3s"
mp3_ext=".mp3"
playlist_ext=".plst"

function main () {
	if [[ "$#" -eq 0 ]]; then
		user-output "$0: invalid argument count (must be > 0)!"
		exit 1
	fi
	while [[ "$#" -gt 0 ]]; do
		case $1 in 
			config)
				shift
				user-output "$0: config handling not configured yet!"
				exit 1
				;;
			*)
				user-output "$0: unrecognised option!"
				shift
				exit 1
				;;
		esac
	done
}

function user-output () {
	local output="$1"
	>&2 echo "$1"
}

main "$@"
