#!/bin/bash

# Hardcoded defaults
#	Immutable
main_directory="$HOME/.playlister/"
config_file="${main_directory}playlister.conf"
database="${main_directory}playlister.db"
helpfile="${main_directory}playlister.help"
playlist_ext=".plst"
mp3_ext=".mp3"
backup_ext=".bak"
#	Mutable
playlist_directory="${main_directory}playlists/"
mp3_directory="/mp3s"

function main () {
	if [[ "$#" -eq 0 ]]; then
		user-output "invalid argument count (must be > 0)!"
		exit 1
	fi
	while [[ "$#" -gt 0 ]]; do
		case $1 in 
			config)
				shift
				config "$@"
				exit 1
				;;
			*)
				user-output "unrecognised option!"
				shift
				exit 1
				;;
		esac
	done
}

function user-output () {
	local output="$1"
	>&2 echo "$0: $1"
}

function config () {
	if [[ "$#" -eq 0 ]]; then
		user-output "invalid config argument count (must be >0)!"
		exit 1
	fi
	while [[ "$#" -gt 0 ]]; do
		case $1 in
			configure)
				config-configure
				exit 1
				;;
			*)
				user-output "unrecognised config option!"
				exit 1
		esac
	done
}
function config-configure () {
	if ! create-directory "$main_directory" ; then
		exit 1
	fi
	
	if ! setup-file "$helpfile" "currentdir"; then
		user-output "failed to set up $helpfile !"
		exit 1
	fi
	
	if ! setup-file "$config_file" "backup" "makenew"; then
		user-output "failed to set up $config_file ."
		exit 1
	else
		if read-config ; then
			user-output "configs read from $config_file ."
		else
			user-output "failed to read configs from $config_file !"
		fi
	fi
}

function create-directory () {
	local directory="$1"
	if [[ -d "$directory" ]]; then
		user-output "$directory already there."
	else
		mkdir $directory
		if [[ $? -ne 0 ]]; then
			user-output "failed to make $directory !"
			return 1
		else
			user-output "made $directory ."
		fi
		
	fi
	return 0
}

function setup-file () {
	local filepath="$1"
	local backup="no"
	local currentdir="no"
	local makenew="no"
	shift
	while [[ "$#" -ne 0 ]]; do
		case $1 in 
			"backup")
				backup="yes"
				shift
				;;
			"currentdir")
				currentdir="yes"
				shift
				;;
			"makenew")
				makenew="yes"
				shift
				;;
			*)
				user-output "unrecognised option!"
				return 1
				;;
		esac
	done
	if [[ -a "$filepath" ]]; then
		user-output "$filepath exists."
		return 0
	fi
	user-output "$filepath does not exist!"

	if [[ "$backup" == "yes" ]]; then
		local filepathbak="${filepath}${backup_ext}"
		if [[ -a "$filepathbak" ]]; then
			user-output "$filepathbak exists."
			cp "$filepathbak" "$filepath"
			if [[ $? -eq 0 ]]; then
				user-output "$filepathbak copied to $filepath ."
				return 0
			fi
			user-output "$filepathbak could not copy to $filepath !"
		else
			user-output "$filepathbak does not exist!"
		fi
	else
		echo "$filepath does not have backup functionality."
	fi

	if [[ "$currentdir" == "yes" ]]; then
		local file="$(basename "$filepath")"
		if ! [[ -a  "$file" ]]; then
			user-output "$file not in current directory!"
		else
			user-output "$file in current directory."
			mv "$file" "$filepath"
			if [[ $? -eq 0 ]]; then
				user-output "$file moved to $filepath ."
				return 0
			else
				user-output "$file failed to move to $filepath !"
			fi
		fi
	fi

	if [[ "$makenew" == "yes" ]]; then
		touch "$filepath"
		if [[ $? -eq 0 ]]; then
			user-output "$filepath created blank."
			return 0
		fi
		user-output "$filepath failed to create blank!"
	fi
	
	return 1
}

function read-config () {
	while read line ; do
		local argument="$(echo "$line" | cut -d "=" -f 1)"
		case "$argument" in
			"mp3_directory")
				local value="$(echo "$line" | cut -d "=" -f 2)"
				mp3_directory="$value"
				;;
			"playlist_directory")
				local value="$(echo "$line" | cut -d "=" -f 2)"
				playlist_directory="$value"
				;;
			*)
				user-output "\"$argument\" is not a valid user config."
				return 1
				;;
		esac
	done < "$config_file"
}

main "$@"
